name: Terraform Deploy S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write #Required for requesting JWT from Github
  contents: read #Required to checkout code. Required explicitely because permissions block is added, otherwise repo content read is default


jobs:

  security-scan:
    name: Checkov security scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          output_format: cli
          soft_fail: true # if false, this will cause the workflow to break if crit/high findings are discovered 


  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS creds via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::426501511660:role/GithubAction-Assume-S3"
          aws-region: "us-east-1"
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve